{"errorMessage": "insert or update on table \"command_log\" violates foreign key constraint \"command_log_number_id_fkey\"\nDETAIL:  Key (number_id)=(999) is not present in table \"numbers\".\n", "errorType": "ForeignKeyViolation", "stackTrace": ["  File \"/var/task/add_log.py\", line 29, in lambda_handler\n    raise(e)\n", "  File \"/var/task/add_log.py\", line 26, in lambda_handler\n    insert_command(command_id, number_id)\n", "  File \"/var/task/add_log.py\", line 12, in insert_command\n    return db.insert(query)\n", "  File \"/opt/python/db.py\", line 33, in insert\n    return query(fn, sql)\n", "  File \"/opt/python/db.py\", line 9, in query\n    cursor.execute(sql)\n"]}